[package]
name = "input_device_test"
version = "1.0.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossbeam-channel = "0.5.15"
crossterm = "0.29.0"
evdev = "0.13.1"
once_cell = "1.21.3"
ratatui = "0.29.0"
serialport = "4.8.1"
